name: Sportsdevos
favicon: null
layout_spectrum: 0.7820235553663224
typography_spectrum: 0.831410099985078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.49329983186908066
  lightness: 0.04932013596408069
  saturation: 0.29624724038876593
  rhythmicContrast: 0.10003525880165398
purpose: []
